<?php
/*
Plugin Name: WooCommerce Export
Plugin URI: https://github.com/joko-wandiro/phc-woocommerce-export
Description: Export WooCommerce Data such as Order, etc easily. 
Version: 1.0.0
Author: Joko Wandiro
Author URI: https://github.com/joko-wandiro/
*/
define("PHC_WOOCOMMERCE_EXPORT_VERSION", "1.0");
define('PHC_WOOCOMMERCE_EXPORT_NAME', "WooCommerce Export");
define('PHC_WOOCOMMERCE_EXPORT_IDENTIFIER', "phc-woocommerce-export");
define('PHC_WOOCOMMERCE_EXPORT_ID_SCRIPT', "phc_woocommerce_export");

load_plugin_textdomain(PHC_WOOCOMMERCE_EXPORT_IDENTIFIER, FALSE, PHC_WOOCOMMERCE_EXPORT_IDENTIFIER . "/languages");

define('PHC_WOOCOMMERCE_EXPORT_FILE', __FILE__);
define('PHC_WOOCOMMERCE_EXPORT_PATH', plugin_dir_path(__FILE__));
define('PHC_WOOCOMMERCE_EXPORT_INCLUDE_PATH', PHC_WOOCOMMERCE_EXPORT_PATH . "inc/");
define('PHC_WOOCOMMERCE_EXPORT_THEME_PATH', PHC_WOOCOMMERCE_EXPORT_PATH . "theme/");
define('PHC_WOOCOMMERCE_EXPORT_PATH_URL', plugin_dir_url(__FILE__));
define('PHC_WOOCOMMERCE_EXPORT_THEME_URL', PHC_WOOCOMMERCE_EXPORT_PATH_URL . "theme/");
define('PHC_WOOCOMMERCE_EXPORT_PATH_URL_CSS', PHC_WOOCOMMERCE_EXPORT_PATH_URL . "css/");
define('PHC_WOOCOMMERCE_EXPORT_PATH_URL_JS', PHC_WOOCOMMERCE_EXPORT_PATH_URL . "js/");
define('PHC_WOOCOMMERCE_EXPORT_IMG_URL', PHC_WOOCOMMERCE_EXPORT_PATH_URL . "img/");
define('PHC_WOOCOMMERCE_EXPORT_IMG_DOCUMENTATION_BOW_TO_USE_URL', PHC_WOOCOMMERCE_EXPORT_PATH_URL . 
"img/documentation/how-to-use/");
define('PHC_WOOCOMMERCE_EXPORT_IMG_DOCUMENTATION_THEMES_URL', PHC_WOOCOMMERCE_EXPORT_PATH_URL . 
"img/documentation/themes/");
define('PHC_WOOCOMMERCE_EXPORT_IMG_DOCUMENTATION_NEW_THEMES_URL', PHC_WOOCOMMERCE_EXPORT_PATH_URL . 
"img/documentation/new-themes/");
define("PHC_WOOCOMMERCE_EXPORT_POST_TYPE", "shop_order");
define("PHC_WOOCOMMERCE_EXPORT_SUBMENU_CAPABILITY", "manage_options");
define("PHC_WOOCOMMERCE_EXPORT_MENU_SLUG", "woocommerce");
define("PHC_WOOCOMMERCE_EXPORT_MENU_SLUG_SETTINGS", PHC_WOOCOMMERCE_EXPORT_ID_SCRIPT . 
"_settings");
define("PHC_WOOCOMMERCE_EXPORT_PAGE_TITLE_SETTINGS", __("Export", PHC_WOOCOMMERCE_EXPORT_IDENTIFIER));
define("PHC_WOOCOMMERCE_EXPORT_MENU_TITLE_SETTINGS", 
PHC_WOOCOMMERCE_EXPORT_PAGE_TITLE_SETTINGS);
define("PHC_WOOCOMMERCE_EXPORT_MENU_SLUG_DOCUMENTATION", PHC_WOOCOMMERCE_EXPORT_ID_SCRIPT . 
"_documentation");
define("PHC_WOOCOMMERCE_EXPORT_PAGE_TITLE_DOCUMENTATION", __("Documentation", PHC_WOOCOMMERCE_EXPORT_IDENTIFIER));
define("PHC_WOOCOMMERCE_EXPORT_MENU_TITLE_DOCUMENTATION", PHC_WOOCOMMERCE_EXPORT_PAGE_TITLE_DOCUMENTATION);

require_once(PHC_WOOCOMMERCE_EXPORT_INCLUDE_PATH . "pages/settings.php");
?>